# -------------------------------------------------------------------------------------
# Summary: Define a base docker-compose file for launching the app.
# Created: 2021-11-11 13:11:15
# Author:  Bryant Finney (https://bryant-finney.github.io/about)
# -------------------------------------------------------------------------------------
x-img-src: &img_src
  org.opencontainers.image.source: ${PROJECT_URL:-https://gitlab.com/django-canary/core}

services:
  db:
    build:
      labels:
        <<: *img_src
      context: ./db
      target: prod
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    image: "${DOCKER_IMAGE_PATH}/db:prod-${DOCKER_VERSION_TAG:-latest}"

  api:
    build:
      labels:
        <<: *img_src
      context: .
      dockerfile: ./api/Dockerfile
      target: prod
    depends_on: [db]
    environment:
      - CANARY_CORE_DB_PASSWORD
      - CANARY_CORE_DB_USER
    image: "${DOCKER_IMAGE_PATH}:prod-${DOCKER_VERSION_TAG:-latest}"
    ports: ["${CORE_API_PORT:-8000}:8000"]
