"""Generated by Django 3.2.9 on 2021-11-14 01:51."""

# django packages
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add field to BasicAPIClient; update Property.

    - add a friendly name field to the BaseAPIClient model
    - allow ``null`` values for ``Property.assessment_date``
    - add an "unknown" option to ``Property.sewage_type``, and make it the default
    """

    dependencies = [
        ("hc_api_connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicapiclient",
            name="name",
            field=models.CharField(
                blank=True, help_text="friendly name of the API client", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="assessment_date",
            field=models.DateField(
                help_text="the date at which the property was assessed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="sewage_type",
            field=models.CharField(
                choices=[
                    ("UN", "Unknown"),
                    ("NO", "None"),
                    ("MU", "Municipal"),
                    ("ST", "Storm"),
                    ("SE", "Septic"),
                    ("YS", "Yes"),
                ],
                default="UN",
                max_length=2,
            ),
        ),
    ]
