# -------------------------------------------------------------------------------------
# Summary: Define a minimal Docker image for the database layer.
# Created: 2021-11-10 20:06:11
# Author:  Bryant Finney (https://bryant-finney.github.io/about)
# -------------------------------------------------------------------------------------
FROM postgres:14-alpine as dev

# intentionally left blank (for now)

FROM dev AS prod

# intentionally left blank (for now)
